from difflib import ndiff, HtmlDiff

def compute_diff_and_stats(textA: str, textB: str) -> dict:
    """
    Returns:
      - diff_list (list of ndiff lines)
      - adds, dels, total
      - add_pct, del_pct
      - html_diff (string generated by HtmlDiff)
      - diff_text (plain \n joined diff lines)
    """
    linesA = textA.splitlines()
    linesB = textB.splitlines()
    diff_list = list(ndiff(linesA, linesB))

    adds = sum(1 for l in diff_list if l.startswith("+ "))
    dels = sum(1 for l in diff_list if l.startswith("- "))
    total = adds + dels
    add_pct = round((adds / total * 100), 2) if total > 0 else 0.0
    del_pct = round((dels / total * 100), 2) if total > 0 else 0.0

    # HtmlDiff table; you can tweak context and wrapcolumn as needed
    html_diff = HtmlDiff(tabsize=4, wrapcolumn=80).make_table(
        linesA, linesB, context=True, numlines=2
    )

    diff_text = "\n".join(diff_list)

    return {
        "diff_list": diff_list,
        "adds": adds,
        "dels": dels,
        "total": total,
        "add_pct": add_pct,
        "del_pct": del_pct,
        "html_diff": html_diff,
        "diff_text": diff_text
    }
